// Mocks generated by Mockito 5.4.6 from annotations
// in currency_converter/test/repositories/currency_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:currency_converter/core/network/network_info.dart' as _i7;
import 'package:currency_converter/data/datasources/local/exchange_rate_local_source.dart'
    as _i6;
import 'package:currency_converter/data/datasources/remote/exchange_rate_remote_source.dart'
    as _i3;
import 'package:currency_converter/data/models/currency.dart' as _i5;
import 'package:currency_converter/data/models/exchange_rate.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExchangeRate_0 extends _i1.SmartFake implements _i2.ExchangeRate {
  _FakeExchangeRate_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExchangeRateRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRateRemoteSource extends _i1.Mock
    implements _i3.ExchangeRateRemoteSource {
  MockExchangeRateRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExchangeRate> getLatestRates(String? baseCurrency) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestRates,
          [baseCurrency],
        ),
        returnValue: _i4.Future<_i2.ExchangeRate>.value(_FakeExchangeRate_0(
          this,
          Invocation.method(
            #getLatestRates,
            [baseCurrency],
          ),
        )),
      ) as _i4.Future<_i2.ExchangeRate>);

  @override
  _i4.Future<List<_i5.Currency>> getAvailableCurrencies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableCurrencies,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Currency>>.value(<_i5.Currency>[]),
      ) as _i4.Future<List<_i5.Currency>>);
}

/// A class which mocks [ExchangeRateLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRateLocalSource extends _i1.Mock
    implements _i6.ExchangeRateLocalSource {
  MockExchangeRateLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExchangeRate?> getCachedRates(String? baseCurrency) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedRates,
          [baseCurrency],
        ),
        returnValue: _i4.Future<_i2.ExchangeRate?>.value(),
      ) as _i4.Future<_i2.ExchangeRate?>);

  @override
  _i4.Future<void> cacheRates(_i2.ExchangeRate? rate) => (super.noSuchMethod(
        Invocation.method(
          #cacheRates,
          [rate],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Currency>> getCachedCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #getCachedCurrencies,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Currency>>.value(<_i5.Currency>[]),
      ) as _i4.Future<List<_i5.Currency>>);

  @override
  _i4.Future<void> cacheCurrencies(List<_i5.Currency>? currencies) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCurrencies,
          [currencies],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
